export const FORMULARIO_PROYECTO = "FORMULARIO_PROYECTO";
export const OBTENER_PROYECTOS = "OBTENER_PROYECTOS";
export const AGREGAR_PROYECTOS = "AGREGAR_PROYECTOS";
export const VALIDAR_FORMULARIO = "VALIDAR_FORMULARIO";
export const PROYECTO_ACTUAL = "PROYECTO_ACTUAL";
export const ELIMINAR_PROYECYO = "ELIMINAR_PROYECYO";
export const PROYECTO_ERROR = "PROYECTO_ERROR";
export const LIMPIAR_PROYECTOS = "LIMPIAR_PROYECTOS";


export const TAREA_PROYECTO = "TAREA_PROYECTO";
export const AGREGAR_TAREA = "AGREGAR_TAREA";
export const VALIDAR_TASK = "VALIDAR_TASK";
export const LIMPIAR_TAREA = "LIMPIAR_TAREA";
export const ELIMINAR_TAREA = "ELIMINAR_TAREA";
export const TAREA_ACTUAL = "TAREA_ACTUAL";
export const ACTUALIZA_TAREA = "ACTUALIZA_TAREA";
export const LIMPIAR_STATE = "LIMPIAR_STATE";



export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";

export const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
export const REGISTRO_ERROR = "REGISTRO_ERROR";
export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CERRAR_SESION = "CERRAR_SESION";