export const FORMULARIO_PROYECTO = "FORMULARIO_PROYECTO";
export const OBTENER_PROYECTOS = "OBTENER_PROYECTOS";
export const AGREGAR_PROYECTOS = "AGREGAR_PROYECTOS";
export const VALIDAR_FORMULARIO = "VALIDAR_FORMULARIO";
export const PROYECTO_ACTUAL = "PROYECTO_ACTUAL";
export const ELIMINAR_PROYECYO = "ELIMINAR_PROYECYO";


export const TAREA_PROYECTO = "TAREA_PROYECTO";
export const AGREGAR_TAREA = "AGREGAR_TAREA";
export const OBTENER_TAREA = "OBTENER_TAREA";
export const VALIDAR_TASK = "VALIDAR_TASK";
export const ELIMINAR_TAREA = "ELIMINAR_TAREA";
export const ESTADO_TAREA = "ESTADO_TAREA";
export const TAREA_ACTUAL = "TAREA_ACTUAL";
export const ACTUALIZA_TAREA = "ACTUALIZA_TAREA";